---
version: '2'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/storage:/data
    network_mode: host
    restart: always
    environment:
      - VERSION=latest
      - PUID=${PUID}
      - PGID=${PGID}
  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    depends_on:
      - plex
    volumes:
      - /opt/appdata/plexpy:/config
      - /opt/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 27029:8181
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  plexrequests:
    image: linuxserver/plexrequests
    container_name: plexrequests
    depends_on:
      - plex
    volumes:
      - /opt/appdata/plexrequests:/config
      - /mnt/storage/tv:/tv
    ports:
      - 27026:3000
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    network_mode: host
    volumes:
      - /opt/appdata/transmission:/config
      - /mnt/disk1/downloads:/downloads
      - /mnt/storage:/mnt/storage
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  owncloud:
    image: owncloud
    ports:
      - 8080:80
    volumes:
      - /opt/appdata/owncloud/apps:/var/www/html/apps
      - /opt/appdata/owncloud/config:/var/www/html/config
      - /mnt/storage/owncloud:/var/www/html/data
  postgres:
    image: postgres
    volumes:
      - /opt/appdata/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=seanssecretpassword
