---
version: '2'
services:
  plex:
    image: plexinc/pms-docker:public
    container_name: plex
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/storage:/data
    network_mode: host
    restart: always
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - CHANGE_CONFIG_DIR_OWNERSHIP=false
 
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    depends_on:
      - plex
    volumes:
      - /opt/appdata/plexpy:/config
      - /opt/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 27029:8181
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
 
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    network_mode: host
    volumes:
      - /opt/appdata/transmission:/config
      - /mnt/disk1/downloads:/downloads
      - /mnt/storage:/mnt/storage
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
 
  owncloud:
    image: owncloud
    ports:
      - 8080:80
    volumes:
      - /opt/appdata/owncloud/apps:/var/www/html/apps
      - /opt/appdata/owncloud/config:/var/www/html/config
      - /mnt/storage/owncloud:/var/www/html/data
 
  postgres:
    image: postgres
    volumes:
      - /opt/appdata/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=seanssecretpassword
