---
version: '2.1'
services:
  plex:
    image: plexinc/pms-docker:public
    container_name: plex
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/storage:/data
      - /mnt/storage/tmp/plex_transcode:/transcode
    network_mode: host
    restart: always
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - CHANGE_CONFIG_DIR_OWNERSHIP=false
 
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    depends_on:
      - plex
    volumes:
      - /opt/appdata/plexpy:/config
      - /opt/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 27029:8181
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
 
  transmission:
    image: haugene/transmission-openvpn 
    container_name: transmission
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0    
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 9091:9091
    volumes:
      - /mnt/disk1/downloads:/data
      - /etc/localtime:/etc/localtime:ro
      - /opt/ovpn:/etc/openvpn/custom
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=27295948_qJ3u7izJXz
      - OPENVPN_PASSWORD=aMYdq85ajm
      - TRANSMISSION_DOWNLOAD_DIR=/data/complete
      - LOCAL_NETWORK=192.168.1.0/24

  owncloud:
    image: library/owncloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - /opt/appdata/owncloud/apps:/var/www/html/apps
      - /opt/appdata/owncloud/config:/var/www/html/config
      - /mnt/storage/owncloud:/var/www/html/data
 
  postgres:
    image: postgres
    volumes:
      - /opt/appdata/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=seanssecretpassword
